name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, development]

jobs:
  build-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"

      - name: Install Electron and misc packages
        shell: bash
        run: |
          npm install
          npm -g install electron